version: '3.8'
services:
  qplay_game_server:
    container_name: qplay_game_server
    image: qplay_game:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
      - "8080:8080"
